Repository Mobile07/Work24, pull requests merged in 2020-10, with the labels that each got.

#6 added packages for organized project structure
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: documentation

#7 I added the verification screen, forgot password, password recovery s…
  .idea/codeStyles/Project.xml
  .idea/misc.xml
  .idea/render.experimental.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pyropy/work24/Forgotpassword.java
  app/src/main/java/com/pyropy/work24/GigPagerAdapter.java
  app/src/main/java/com/pyropy/work24/JobPagerAdapter.java
  app/src/main/java/com/pyropy/work24/MyGigScreen.java
  app/src/main/java/com/pyropy/work24/MyGigsFragment.java
  app/src/main/java/com/pyropy/work24/MyJobScreen.java
  app/src/main/java/com/pyropy/work24/MyJobsFragment.java
  app/src/main/java/com/pyropy/work24/PasswordRecovery.java
  app/src/main/java/com/pyropy/work24/SavedGigFragment.java
  app/src/main/java/com/pyropy/work24/SavedJobsFragment.java
  app/src/main/java/com/pyropy/work24/verification.java
  app/src/main/res/drawable/back_icon.JPG
  app/src/main/res/drawable/back_to_login.xml
  app/src/main/res/drawable/backicon.jpg
  app/src/main/res/drawable/check_emaiil.png
  app/src/main/res/drawable/check_email.png
  app/src/main/res/drawable/forgot_password.jpg
  app/src/main/res/drawable/forgot_password_1.jpg
  app/src/main/res/drawable/inputemail_details.xml
  app/src/main/res/drawable/reset_password.xml
  app/src/main/res/drawable/white_envelope.jpg
  app/src/main/res/drawable/whiteenvelope.jpg
  app/src/main/res/layout/activity_forgotpassword.xml
  app/src/main/res/layout/activity_my_gig_screen.xml
  app/src/main/res/layout/activity_my_job_screen.xml
  app/src/main/res/layout/activity_password_recovery.xml
  app/src/main/res/layout/activity_verification.xml
  app/src/main/res/layout/fragment_my_gigs.xml
  app/src/main/res/layout/fragment_my_jobs.xml
  app/src/main/res/layout/fragment_saved_gig.xml
  app/src/main/res/layout/fragment_saved_jobs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement

#8 reorganizing submitted tasks by Oluwadarafunmi
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pyropy/work24/GigPagerAdapter.java
  app/src/main/java/com/pyropy/work24/JobPagerAdapter.java
  app/src/main/java/com/pyropy/work24/MyGigScreen.java
  app/src/main/java/com/pyropy/work24/MyJobScreen.java
  app/src/main/java/com/pyropy/work24/views/activities/Forgotpassword.java
  app/src/main/java/com/pyropy/work24/views/activities/MyGigScreen.java
  app/src/main/java/com/pyropy/work24/views/activities/MyJobScreen.java
  app/src/main/java/com/pyropy/work24/views/activities/PasswordRecovery.java
  app/src/main/java/com/pyropy/work24/views/activities/verification.java
  app/src/main/java/com/pyropy/work24/views/adapters/GigPagerAdapter.java
  app/src/main/java/com/pyropy/work24/views/adapters/JobPagerAdapter.java
  app/src/main/java/com/pyropy/work24/views/fragments/MyGigsFragment.java
  app/src/main/java/com/pyropy/work24/views/fragments/MyJobsFragment.java
  app/src/main/java/com/pyropy/work24/views/fragments/SavedGigFragment.java
  app/src/main/java/com/pyropy/work24/views/fragments/SavedJobsFragment.java
  app/src/main/res/layout/activity_forgotpassword.xml
  app/src/main/res/layout/activity_my_gig_screen.xml
  app/src/main/res/layout/activity_my_job_screen.xml
  app/src/main/res/layout/activity_password_recovery.xml
  app/src/main/res/layout/activity_verification.xml
  app/src/main/res/layout/fragment_my_gigs.xml
  app/src/main/res/layout/fragment_my_jobs.xml
  app/src/main/res/layout/fragment_saved_gig.xml
  app/src/main/res/layout/fragment_saved_jobs.xml
  app/src/main/res/values/strings.xml
Labels: error fix

#9 Splash screen
  .idea/codeStyles/Project.xml
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pyropy/work24/MyAppIntroActivity.kt
  app/src/main/java/com/pyropy/work24/SplashScreen.java
  app/src/main/res/drawable/welcome.jpg
  app/src/main/res/drawable/welcome2.jpg
  app/src/main/res/drawable/work1.jpg
  app/src/main/res/drawable/work2.jpg
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/raw/work.mp4
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement
